### ISSUE TITLE
Add support for composer

### ISSUE THREAD

**Issue by fwahlqvist** [EvanDotPro/EdpMarkdown#4]
Hi Evan,
Would be great if you could add composer support for this module

**Comment by EvanDotPro** [comment]
Hi! Sorry it's taken me so long to get around to the issues on my repos. I plan on adding composer/travis support on all of my modules/projects pretty soon.

**Comment by EvanDotPro** [comment]
Composer/packagist support is enabled starting from v0.2.0.
